### PR TITLE
Fix run exports

### LINKED ISSUE #13: The `run_exports` are not working?
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Using `- numactl` in host requirements should lead to the inclusion of `- libnuma` in the run requirements, but doesn't seem to. I think this is because `run_exports` is listed in the parent build section, but should be in the `numactl` output's build seciont.

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

### PR DESCRIPTION
**Pull request by zklaus**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #13

### CODE REVIEW

**Comment by zklaus** [comment]
@conda-forge-admin, please rerender

**Review by kkraus14 — APPROVED** [review]

**Comment by zklaus** [comment]
@chrisburr, friendly ping. Looks like @kkraus14 would like your opinion before merging. Me too, obviously :smile:

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Comment by kkraus14** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
